[app]
ns="Nuxt3Deploy"
stage="Dev"

[aws]
region="ap-northeast-2"

[build]
path='.'

#[domain]
# acmCertArn=""
# altDomains=[""]

[repository]
name="nuxt3-deploy"
branch="main"
region="ap-northeast-2"

#[notification]
#hookUrl=""